# -*- coding: utf-8 -*-
"""COMPONENT / constructor isolation tests. Production regression is in
test_authoritative_skill_no_skill_integration_regression_v1.py.
"""

from __future__ import annotations

import pytest

from scripts.sgs_engine.actions import ActionContext
from scripts.sgs_engine.authoritative_no_skill_full_game import (
    AUTHORITATIVE_NO_SKILL_FULL_GAME_V1_CONTRACT_ID,
    AUTHORITATIVE_NO_SKILL_REPLAY_V2_SCHEMA,
    CanonicalNoSkillModeV1,
    canonical_no_skill_mode_v1,
)
from scripts.sgs_engine.engine import DEFAULT_DECK_PATH
from scripts.sgs_engine.formal_duel import (
    FormalDuelConfiguration,
    FormalNoSkillDuelSession,
    deck_identity,
    implementation_identity,
)
from scripts.sgs_engine.mode_2v2 import (
    FORMAL_NO_SKILL_2V2_MODE,
    Formal2v2Configuration,
    Formal2v2Session,
)
from scripts.sgs_engine.mode_doudizhu import (
    FORMAL_NO_SKILL_DOUDIZHU_MODE,
    FormalDoudizhuConfiguration,
    FormalDoudizhuSession,
)
from scripts.sgs_engine.mode_identity import (
    FORMAL_NO_SKILL_IDENTITY_5P_MODE,
    FORMAL_NO_SKILL_IDENTITY_8P_MODE,
    FormalEightPlayerIdentityConfiguration,
    FormalEightPlayerIdentitySession,
    FormalIdentityConfiguration,
    FormalIdentitySession,
)
from scripts.sgs_engine.mode_identity_heir import (
    FORMAL_NO_SKILL_IDENTITY_8P_HEIR_MODE,
    FormalHeirAndSpyChoiceIdentityConfiguration,
    FormalHeirAndSpyChoiceIdentitySession,
)
from scripts.sgs_engine.production_batch import FORMAL_NO_SKILL_DUEL_MODE
from scripts.sgs_engine.skill_registry import EMPTY_SKILL_REGISTRY
from scripts.sgs_engine.skill_runtime import AuthoritativeSkillRuntime


def test_empty_skill_registry_guarantees() -> None:
    """EMPTY_SKILL_REGISTRY is frozen, contains 0 skills, and produces 0 actions."""
    assert EMPTY_SKILL_REGISTRY.is_frozen
    assert len(EMPTY_SKILL_REGISTRY.skills) == 0
    assert len(EMPTY_SKILL_REGISTRY.skill_ids) == 0
    assert EMPTY_SKILL_REGISTRY.registry_identity != ""

    runtime = AuthoritativeSkillRuntime(EMPTY_SKILL_REGISTRY)
    assert len(runtime.player_skills) == 0

    session = FormalNoSkillDuelSession(configuration=FormalDuelConfiguration.formal_profile(), seed=1)
    context = ActionContext(mode="formal_duel", phase="play", actor_id="p1")
    actions = runtime.enumerate_active_skill_actions("p1", context, session.state)
    assert len(actions) == 0


def test_no_skill_constructors_have_no_skill_runtime_fields() -> None:
    """All 6 formal no-skill session configurations maintain their existing schemas without skill fields."""
    c_duel = FormalDuelConfiguration.formal_profile()
    assert not hasattr(c_duel, "skill_registry")

    c_2v2 = Formal2v2Configuration.formal_profile()
    assert not hasattr(c_2v2, "skill_registry")

    c_ddz = FormalDoudizhuConfiguration.formal_profile()
    assert not hasattr(c_ddz, "skill_registry")

    c_id5 = FormalIdentityConfiguration.formal_profile()
    assert not hasattr(c_id5, "skill_registry")

    c_id8 = FormalEightPlayerIdentityConfiguration.formal_profile()
    assert not hasattr(c_id8, "skill_registry")

    c_heir = FormalHeirAndSpyChoiceIdentityConfiguration.formal_profile()
    assert not hasattr(c_heir, "skill_registry")


def test_no_skill_modes_execute_normally() -> None:
    """A representative no-skill duel session initializes and runs cleanly without skill interference."""
    config = FormalDuelConfiguration.formal_profile()
    session = FormalNoSkillDuelSession(configuration=config, seed=42)

    assert session.state is not None
    assert len(session.state.cards) == 160
    assert session.is_finished is False

    # Legal actions generated by no-skill session contain no skill actions
    legal_actions = session.legal_actions()
    assert all(a.action_type != "activate_skill" for a in legal_actions)
    assert all(a.skill_id is None for a in legal_actions)


def test_authoritative_no_skill_registry_mode_manifest_intact() -> None:
    """The 6 canonical modes in canonical_no_skill_mode_v1 remain intact."""
    modes = (
        FORMAL_NO_SKILL_DUEL_MODE,
        FORMAL_NO_SKILL_2V2_MODE,
        FORMAL_NO_SKILL_DOUDIZHU_MODE,
        FORMAL_NO_SKILL_IDENTITY_5P_MODE,
        FORMAL_NO_SKILL_IDENTITY_8P_MODE,
        FORMAL_NO_SKILL_IDENTITY_8P_HEIR_MODE,
    )
    for m in modes:
        mode_obj = canonical_no_skill_mode_v1(m)
        assert mode_obj.mode_id == m
